version: '3.8'

services:
  balancer:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    environment:
      - CONFIG_PATH=./config/config.yaml
    depends_on:
      - redis
      - backend1
      - backend2
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./test-backends/backend1.html:/usr/share/nginx/html/index.html
    networks:
      - app-network

  backend2:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./test-backends/backend2.html:/usr/share/nginx/html/index.html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge